name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Apply the custom resource definition
      run: kubectl apply -f echoes.example.com.yaml

    - name: Run the operator
      run: cargo run &

    - name: Apply the custom resource after a few seconds
      run: sleep 2 && kubectl apply -f echo-example.yaml

    - name: Validate that the deployment has been created after a few seconds
      run: sleep 10 && kubectl get deployments | grep "test-echo"
